### ISSUE TITLE
library.properties -> paragraph must be without LF

### ISSUE THREAD

**Issue by reaper7** [imerso/ESPWebConfig#1]
paragraph value must be in one line without LF because it cause error:

`Property line 'the transceiver, where you can change between Access Point and Station' in file C:\PROGRAMY\arduino_projekty\libraries\ESPWebConfig\library.properties is invalid`

**Comment by imerso** [comment]
Thank you, it has been fixed today.

**Comment by reaper7** [comment]
now compilation is ok :)
tnx!
